name: Tokate
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review, converted_to_draft, labeled, unlabeled, assigned, unassigned]
permissions: {}
jobs:
  coordinate:
    permissions:
      contents: write
      issues: read
      pull-requests: write
    uses: obselate/tokate/.github/workflows/tokate-shared.yml@06092f3428114677961435db7a12a04de2aff748
    with:
      archive_url: 'https://api.github.com/repos/obselate/tokate/releases/assets/625102751'
      archive_sha256: 'f8d93e7cfd3366be37af9b90e2fe8232649656240060effd0e5904e71c2db39e'
      member: 'tokate-0.3.5-linux-x64/tokate'
